kz_kwiz_homepage:
    path:     /
    defaults: { _controller: KZKwizBundle:Default:index }

kz_kwiz_new_game:
    path:     /newGame
    defaults: { _controller: KZKwizBundle:Party:new}

kz_kwiz_joinParty:
    path:     /joinParty/{id}
    defaults: { _controller: KZKwizBundle:Party:index, id: 0 }

kz_kwiz_game:
    path:     /game/{id}
    defaults: { _controller: KZKwizBundle:Game:index }

kz_kwiz_test:
    path:     /test/{party}
    defaults: { _controller: KZKwizBundle:Game:random }


kz_kwiz_carte:
    path:     /carte
    defaults: { _controller: KZKwizBundle:Carte:index }

kz_kwiz_endGame:
    path:     /game/history/{id}
    defaults: { _controller: KZKwizBundle:Game:history }

